### ISSUE TITLE
Deploy master.node on docker version

### ISSUE THREAD

**Issue by Zerapio123** [GluuFederation/gluu-engine#106]
I have created an AWS provider.
Connecting to this provider is done automatically when you create the new node on the UI or the terminal 
After waiting for the provider instances to be running I check the logs by using 
"tailf /var/log/gluuengine/node.log"

Problem is that while it says:
"2016-11-02 14:39:52,901 - gluu-master - INFO  - creating gluu-master node (master)"
It stops there without giving me any errors or doing anything really so I have no idea what could be wrong with it

**Comment by iromli** [comment]
@Zerapio123 it could be network issue in AWS. Try deleting the node and recreate it.

**Comment by iromli** [comment]
@shouro 

> It stops there without giving me any errors or doing anything really so I have no idea what could be wrong with it

perhaps we need to make the log a little bit verbose?

**Comment by Zerapio123** [comment]
I did it again. Here is where it stops 
![gluu](https://cloud.githubusercontent.com/assets/22101565/19940965/bf221f58-a104-11e6-9bce-b441ec665cdd.PNG)

**Comment by Zerapio123** [comment]
It just stops there. 
![image](https://cloud.githubusercontent.com/assets/22101565/19940998/dbb5898e-a104-11e6-9a53-324c9f3688ed.png)

Thats my AWS

**Comment by Zerapio123** [comment]
Worked. Just took me like 1 hour and half

**Comment by shouro** [comment]
We are using docker-machine under the hood. We will look  into this (why it took this long time on t2.micro type vm) and try to add relevant log if possible.

**Comment by Zerapio123** [comment]
Thanks
