### ISSUE TITLE
Installing the community edition

### ISSUE THREAD

**Issue by Zerapio123** [GluuFederation/gluu-engine#110]
Hello guys im trying to install the community edition of Gluu Server but I keep getting this page on the link after I finish the setup. I've been going through the youtube videos of the installation and the documentation and can't find a solution. Could you plz help 

![image](https://cloud.githubusercontent.com/assets/22101565/20492723/e0f92d2c-afe3-11e6-9847-6411478ac27f.png)

**Comment by willow9886** [comment]
Hello,

All issues need to e reported via http://support.gluu.org.

Thank you.
