### ISSUE TITLE
Rename the project (and optionally the package namespace)

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-engine#36]
According to http://flask.pocoo.org/docs/0.10/extensiondev/#approved-extensions:

> 5. The naming scheme for official extensions is Flask-ExtensionName or ExtensionName-Flask.

As we use `gluu-flask` as project name, sooner or later it will confuse others. People probably will assume that this project is a Flask extension to interact with Gluu API. Hence I would suggest changing the name for clarity.

Personally, I'd like to use `gluu-api` as project name and keep the Python package namespace remain intact (`gluuapi`). But perhaps there's another name that **describes** the purpose of this project.

I'm open to any idea.

**Comment by nynymike** [comment]
Perhaps gluu-api is too generic. Gluu has many API's... OpenID Connect, Uma, and Scim are all API's. How about gluu-cluster-api or gluu-deployment-api ?

**Comment by iromli** [comment]
How about gluu-cluster?

**Comment by shouro** [comment]
I suggest gluu-engine

**Comment by iromli** [comment]
the package will be renmaed after all features and bugfixes merged to master.

**Comment by iromli** [comment]
Renamed.
