### ISSUE TITLE
Change node log location

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-engine#86]
Currently, every node log message is saved to `/tmp/node.log`. It should be moved to `/var/lib/gluu-cluster/node.log` directory.

**Comment by shouro** [comment]
```/var/log/gluu/node.log``` or ```/var/lib/gluu-cluster/node.log```

**Comment by iromli** [comment]
`/var/log/gluu-cluster/node.log`

**Comment by shouro** [comment]
using /var/log/gluu/node.log

On Fri, May 27, 2016 at 6:50 AM, Isman Firmansyah <notifications@github.com>
wrote:

> /var/log/gluu-cluster/node.log
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GluuFederation/gluu-engine/issues/86#issuecomment-222033941>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAFlFtMhoqkQiOMjS2xA_fYVz005U5wgks5qFj--gaJpZM4InOsd>
> .
>



-- 
$ whatis themeaningoflife
$ themeaningoflife: nothing appropriate

http://shouro.blogspot.com

**Comment by iromli** [comment]
> using /var/log/gluu/node.log

Yes. Sorry i was confused about the path.

**Comment by iromli** [comment]
Fixed in 1de571d2087f855d79b9fdc959b3e2400a5f3d41
