### ISSUE TITLE
dynamic container deploy update for oxauth and oxidp

### ISSUE THREAD

**Issue by shouro** [GluuFederation/gluu-engine#87]
to deploy many oxauth and oxidp at once.

**Comment by nynymike** [comment]
More concerned about oxauth then oxidp right now...

**Comment by shouro** [comment]
This will not pushed before demo.

**Comment by iromli** [comment]
Any news about the progress?

**Comment by shouro** [comment]
scale up is done for containers, will start working on scale down.
