### ISSUE TITLE
Gluu provided get docker scrip

### ISSUE THREAD

**Issue by shouro** [GluuFederation/gluu-engine#90]
To set docker version in node deployment.

**Comment by iromli** [comment]
A workaround is to download script from https://get.docker.com/, modify few lines to install specific docker-engine version, then put it in our website, e.g. get-docker.gluu.org.

What do you think?

**Comment by shouro** [comment]
yes, thinking exactly the same, we can put it in github, under cluster tools

**Comment by iromli** [comment]
Tested. Worked like a charm. Thanks @shouro
