### ISSUE TITLE
Replace subprocess calls in copy_to_container and copy_from_container

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-engine#95]
The `copy_to_container` and `copy_from_container` methods in `dockerclient._docker.Docker` require subprocess to call `docker cp`.

To make a dockerized `gluuengine`, we need to replace those calls (in order to remove docker executable dependency inside the `gluuengine` image).

* [x] re-implement `copy_to_container`
* [x] re-implement `copy_from_container`

**Comment by iromli** [comment]
Merged to `master`

**Comment by shouro** [comment]
+1
